repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v2.3.0
  #   hooks:
  #     - id: flake8
  #       stages:
  #          - push
  - repo: local
    hooks:
      - id: line_count
        name: Line Count
        stages:
          - commit
        entry: hooks.sh
        language: script
