repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        stages:
          - commit
  - repo: local
    hooks:
      - id: validate_examples
        name: Validate Examples
        stages:
          - commit
        entry: hooks.sh
        language: script
