repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        stages:
          - commit
  - repo: local
    hooks:
      - id: frontend_checks
        name: Frontend Checks
        stages:
          - commit
        entry: ./.tests/pre-commit-frontend.sh
        language: script
