repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/sebdah/git-pylint-commit-hook
    rev: 2.5.1
    hooks:
    - id: pylint
      language_version: python3
