repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--filter-files', '--check']
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.192
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: ['--force-exclude']
  - repo: local
    hooks:
      - id: typescript
        name: TypeScript
        files: 'hyperglass/ui/*'
        exclude: 'hyperglass/ui/node_modules|hyperglass/ui/.next'
        stages:
          - commit
        entry: ./.tests/pre-commit-frontend.sh --typescript
        language: script
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        files: 'hyperglass/ui/*'
        exclude: 'hyperglass/ui/node_modules|hyperglass/ui/.next'
        stages:
          - commit
        entry: ./.tests/pre-commit-frontend.sh --eslint
        language: script
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        files: 'hyperglass/ui/*'
        exclude: 'hyperglass/ui/node_modules|hyperglass/ui/.next'
        stages:
          - commit
        entry: ./.tests/pre-commit-frontend.sh --prettier
        language: script
