repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        stages:
          - commit
  - repo: local
    hooks:
      - id: typescript
        name: Frontend TypeScript Check
        files: 'hyperglass/ui/*'
        exclude: 'hyperglass/ui/node_modules|hyperglass/ui/.next'
        stages:
          - commit
        entry: ./hyperglass/ui/node_modules/.bin/tsc
        language: script
  - repo: local
    hooks:
      - id: eslint
        name: Frontend ESLint Check
        files: 'hyperglass/ui/*'
        exclude: 'hyperglass/ui/node_modules|hyperglass/ui/.next'
        stages:
          - commit
        entry: ./hyperglass/ui/node_modules/.bin/eslint .
        language: script
  - repo: local
    hooks:
      - id: prettier
        name: Frontend Prettier Check
        files: 'hyperglass/ui/*'
        exclude: 'hyperglass/ui/node_modules|hyperglass/ui/.next'
        stages:
          - commit
        entry: ./hyperglass/ui/node_modules/.bin/prettier -c -w .
        language: script
