language: python
python:
- '3.6'
before_install:
- sudo add-apt-repository universe -y
- sudo apt-get update -q
- sudo apt-get install -y redis-server redis-tools
- sudo systemctl start redis-server
install:
- pip3 install -r requirements.txt
before_script:
- pip3 install -r ./tests/requirements_dev.txt
- pip3 install anybadge
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git checkout master
- black hyperglass
- git add hyperglass/ *.py
- git commit --message "Black Formatting - travis \#$TRAVIS_BUILD_NUMBER"
- python3 ./manage.py pylint-badge --integer-only True
- git add pylint.svg
- git commit --message "Pylint Badge - travis \#$TRAVIS_BUILD_NUMBER"
- python3 ./tests/ci_prepare.py
script:
- nohup python3 ./tests/ci_dev_server.py &
- sleep 20
- python3 ./tests/ci_test.py
after_success:
- git push origin master
