language: python
python:
  - "3.6"
before_install:
  - sudo bash ./ci/ci_dependencies.sh
  - pip3 install black
  - pip3 install pylint
install:
  - pip3 install -r requirements.txt
before_script:
  - bash ./ci/check_code.sh
script:
  - python3 ./ci/ci_test.py
after_script:
  - bash ./ci/ci_commit.shs
