language: python
python:
- '3.6'
before_install:
- sudo add-apt-repository universe -y
- sudo apt-get update -q
- sudo apt-get install -y redis-server redis-tools
- sudo systemctl start redis-server
- pip3 install -r ./tests/requirements_dev.txt
install:
- pip3 install -r requirements.txt
after_install:
- bash ./tests/check_code.sh
before_script:
- python3 ./tests/ci_prepare.py
script:
- nohup python3 ./tests/ci_dev_server.py &
- sleep 20
- python3 ./tests/ci_test.py
after_success:
- git remote add origin https://${GH_TOKEN}@github.com/checktheroads/hyperglass.git > /dev/null 2>&1
- git push --quiet --set-upstream origin master
