---
language: minimal
dist: bionic

jobs:
  include:
    - stage: Lint
      services:
        - docker
      before_install:
        - docker build -t hyperglass/ubuntu -f .tests/app/ubuntu/Dockerfile .
      script: docker run hyperglass/ubuntu /bin/sh -c "cd /tmp/hyperglass; poetry run flake8 hyperglass"
    - stage: Installer - Ubuntu
      services:
        - docker
      before_install:
        - docker build -t install_ubuntu -f .tests/install/ubuntu/Dockerfile .
      script: docker run install_ubuntu /bin/bash /tmp/install.sh
    - stage: App - Ubuntu
      services:
        - docker
        - redis
      before_install:
        - docker build -t hyperglass/ubuntu -f .tests/app/ubuntu/Dockerfile .
      env:
        - HYPERGLASS_UI_BUILD_TIMEOUT=600
      script: docker run hyperglass/ubuntu /tmp/setup.sh
      # Poetry & PyPI Deployment stolen from: https://github.com/python-poetry/poetry/issues/366
    - stage: Publish
      script: skip
      before_deploy:
        - pip install poetry
        - poetry config pypi-token.pypi $PYPI_TOKEN
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          branch: v1.0.0
