---

language: python
python:
    - '3.7'
before_install:
    - sudo add-apt-repository universe -y
    - sudo apt-get update -q
    - sudo apt-get install -y redis-server redis-tools
    - sudo systemctl start redis-server --bind 127.0.0.1
    - sudo systemctl status redis-server
install:
    - pip3 install -r requirements.txt
before_script:
    - pip3 uninstall -y -r ./tests/requirements_dev.txt
    - pip3 install -r ./tests/requirements_dev.txt
    - isort -rc hyperglass
    - flake8 hyperglass
    - python3 ./tests/ci_prepare.py
script:
    - nohup python3 ./tests/ci_dev_server.py &
    - sleep 20
    - python3 ./tests/ci_test.py
