---
language: minimal
services:
  - docker
  - redis
before_install:
  - docker build -t hyperglass/ubuntu -f .tests/DockerfileUbuntu .

jobs:
  include:
    - stage: Lint
      script: docker run hyperglass/ubuntu /bin/sh -c "cd /tmp/hyperglass; poetry run flake8 hyperglass"
    - stage: Test
      script: docker run hyperglass/ubuntu /tmp/dockersetup.sh
