language: python
python:
  - "3.6"
before_install:
  - sudo add-apt-repository universe -y
  - sudo apt-get update -q
  - sudo apt-get install -y redis-server redis-tools
  - sudo systemctl start redis-server
  - pip3 install -r ./ci/requirements_dev.txt
install:
  - pip3 install -r requirements.txt
before_script:
  - bash ./ci/check_code.sh
script:
  - python3 ./ci/ci_test_prepare.py &
  - python3 ./ci/ci_test.py
after_script:
  - bash ./ci/ci_commit.shs
