site_name: 'hyperglass documentation'
site_author: 'checktheroads | Matt Love'
site_url: 'https://hyperglass.readthedocs.io'
copyright: ''
nav:
    - Home: 'index.md'
    - Installation:
      - 'Installing Hyperglass': 'installation/installing-hyperglass.md'
      - 'HTTP/WSGI': 'installation/wsgi.md'
      - 'Systemd': 'installation/systemd.md'
      - 'Reverse Proxy & SSL': 'installation/reverseproxy.md'
    - Configuration:
      - 'Configuring Hyperglass': 'configuration/index.md'
      - 'General Parameters': 'configuration/general.md'
      - 'Branding': 'configuration/branding.md'
      - 'Devices': 'configuration/devices.md'
    - Caching: 'caching.md'
    - Rate Limiting: 'ratelimiting.md'
    - Development:
      - 'Introduction': 'development/index.md'
    - Extras:
      - 'Common AS_PATH Regular Expressions': 'extras/common_as_path_regex.md'
      - 'Securing Router Access': 'extras/securing-router-access.md'
      - 'Supported Device Types': 'extras/supported-device-types.md'
# Theme Configuration
theme:
  name: 'readthedocs'
# Extensions
markdown_extensions:
  - admonition
  - pymdownx.mark
  - toc:
      permalink: true
      toc_depth: 1-3
# Social Links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/checktheroads/hyperglass'
