[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "hyperglass"
version = "1.0.0"
description = "hyperglass is a modern, customizable network looking glass written in Python 3."
authors = ["checktheroads <matt@allroads.io>"]
license = "BSD-3-Clause-Clear"

[tool.poetry.dependencies]
python = "^3.7"
aredis = "^1.1.7"
click = "^7.0"
cryptography = "^2.8"
hiredis = "^1.0.1"
httpx = "^0.9"
Jinja2 = "^2.10.3"
loguru = "^0.4.0"
markdown2 = "^2.3.8"
netmiko = "^2.4.2"
passlib = "^1.7.2"
prometheus_client = "^0.7.1"
pydantic = "^1.3"
PyJWT = "^1.7.1"
PyYAML = "^5.2"
redis = "^3.3.11"
sanic-limiter = "^0.1.3"
sanic = "^19.12.2"
sshtunnel = "^0.1.5"
stackprinter = "^0.2.3"
uvloop = "^0.14.0"
aiofile = "^1.5.2"
requests = "^2.22.0"

[tool.poetry.dev-dependencies]
anybadge = "^1.6.2"
black = "^19.10b0"
isort = "^4.3.21"
bandit = "^1.6.2"
flake8 = "^3.7.9"
flake8-bandit = "^2.1.2"
flake8-black = "^0.1.1"
flake8-breakpoint = "^1.1.0"
flake8-bugbear = "^20.1.0"
flake8-builtins = "^1.4.2"
flake8-comprehensions = "^3.1.4"
flake8-deprecated = "^1.3"
flake8-eradicate = "^0.2.4"
flake8-if-expr = "^1.0.0"
flake8-isort = "^2.8.0"
flake8-pie = "^0.4.2"
flake8-plugin-utils = "^1.0.0"
flake8-polyfill = "^1.0.2"
flake8-print = "^3.1.4"
flake8-return = "^1.1.1"
pep8-naming = "^0.9.1"
flake8-docstrings = "^1.5.0"
pre-commit = "^1.21.0"

[tool.isort]
line_length = 88
indent = '    '
force_single_line = true
import_heading_stdlib = "Standard Library Imports"
import_heading_thirdparty = "Third Party Imports"
import_heading_firstparty = "Project Imports"

[tool.black]
line-length = 88
