---
name: New Platform
description: Request native support for a network operating system/platform
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: >
        In order to natively support a new platform for hyperglass, please make sure it is supported by Netmiko ([see here](https://hyperglass.dev/platforms)).
  - type: input
    attributes:
      label: Manufacturer
      description: What is the network vendor? For example, for Juniper Junos, this would be Juniper.
    validations:
      required: true
  - type: input
    attributes:
      label: Name
      description: What is the name of this platform? For example, for Juniper Junos, this would be Junos
    validations:
      required: true
  - type: textarea
    attributes:
      label: Commands
      description: >
        Please provide the commands required to execute the default hyperglass commands (IPv4 BGP Route, IPv6 BGP Route, BGP AS Path, BGP Community, IPv4 ping, IPv6 ping, IPv4 traceroute, and IPv6 traceroute). If you do not know the commands, it is likely that this request will be either denied or may take a long time to implement.
