name: Backend Testing
on:
  - push
  - pull_request

jobs:
  backend:
    name: Backend Tests
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        redis-version: [5, 6]
        poetry-version: [1.1.11]
        python-version: [3.8, 3.9]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Prepare
        run: |
          echo "HYPERGLASS_APP_PATH=$HOME/hyperglass" >> $GITHUB_ENV
          mkdir $HYPERGLASS_APP_PATH

      - name: Install (Poetry)
        run: poetry install

      - name: Lint (Flake8)
        run: poetry run task lint

      - name: Test (PyTest)
        run: poetry run task test

      - name: Run hyperglass
        run: '.tests/ga-backend-app.sh'
