name: Frontend Testing
on:
  - push
  - pull_request

jobs:
  frontend:
    name: Frontend Tests
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./hyperglass/ui
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: ${{ env.working-directory }}
        run: yarn install

      - name: Formatting (Prettier)
        working-directory: ${{ env.working-directory }}
        run: yarn format:check

      - name: Lint (ESLint)
        working-directory: ${{ env.working-directory }}
        run: yarn lint

      - name: Types (TypeScript)
        working-directory: ${{ env.working-directory }}
        run: yarn typecheck

      - name: Tests (Jest)
        working-directory: ${{ env.working-directory }}
        run: yarn test
