name: Frontend Testing
on: [push, pull_request]

jobs:
  frontend:
    name: Type Check
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./hyperglass/ui
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        working-directory: ${{ env.working-directory }}
        run: yarn install

      - name: TypeScript Check
        working-directory: ${{ env.working-directory }}
        run: yarn typecheck
