name: Installer Testing
on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Run hyperglass
        run: 'sudo bash ./install.sh'
