name: Installer Testing
on:
  - push
  - pull_request

jobs:
  installer:
    name: Installer Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Run hyperglass
        run: 'sudo bash ./install.sh'
