# name: Run Tests
# on:
#   push:
#     branches:
#       - v1.0.0

# jobs:
#   build:
#     runs-on: ubuntu-18.04
#     services:
#       redis:
#         image: redis
#         ports:
#           - 6379:6379
# steps:
#   - name: Setup Python 3.6
#     uses: actions/setup-python@v1
#     with:
#       python-version: 3.6.10
#   - name: Clone Repository
#     uses: actions/checkout@v2
#     with:
#       ref: v1.0.0
#   - name: Install Poetry
#     uses: dschep/install-poetry-action@v1.3
#   - name: Install Python Dependencies
#     run: poetry install
#   - name: Lint
#     run: poetry run flake8 hyperglass
