name: Run Tests
on:
  push:
    branches:
      - v1.0.0

jobs:
  build:
    runs-on: ubuntu-18.04
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.10
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          ref: v1.0.0
      - name: Install Application
        run: |
          'curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python'
          poetry --version
          poetry install
          poetry run flake8 hyperglass
      # - name: Install Python Dependencies
      #   run: |
      #     pip install --user pipx
      #     export PATH=/home/runner/.local/bin:$PATH
      #     pipx ensurepath
      #     pipx install poetry
      # - name: Install Application
      #   uses: abatilo/actions-poetry@v1.5.0
      #   with:
      #     python_version: 3.6.10
      #     poetry_version: 1.0.0
      #     args: install && run flake8 hyperglass
      # - name: Lint
      #   uses: abatilo/actions-poetry@v1.5.0
      #   with:
      #     python_version: 3.6.10
      #     poetry_version: 1.0.0
      #     args: run flake8 hyperglass
      # - name: lint
      #   uses: ricardochaves/python-lint@v1.1.0
      #   with:
      #     python-root-list: hyperglass
      #     use-black: true
      #     use-flake8: true
      #     use-isort: true
      #     use-pylint: false
      #     use-pycodestyle: false
      #     use-mypy: false
      #     extra-pylint-options: ""
      #     extra-pycodestyle-options: ""
      #     extra-flake8-options: ""
      #     extra-black-options: ""
      #     extra-mypy-options: ""
      #     extra-isort-options: ""
